### ISSUE TITLE
can run my custom video?

### ISSUE THREAD

**Issue by alexlugovsk** [924973292/DeMo#3]
Can I use this demo to run my videos through your pre-trained models (without any additional training on my part). The output would be a video file with re-identification or distribution of persons by folders in the file system. Is this possible with this demo without any modifications?

**Comment by 924973292** [comment]
Thank you for your interest. DeMo is designed for multi-modal ReID, taking multi-modal image inputs and producing a global retrieval vector as output. Without modifications, it cannot meet the requirements of your task.
