### ISSUE TITLE
ViT-B

### ISSUE THREAD

**Issue by JustBreeze** [924973292/DeMo#4]
ViT-B: [Baidu Pan](https://pan.baidu.com/s/1YE-24vSo5pv_wHOF-y4sfA) 
What's the code?

**Comment by 924973292** [comment]
It should be: vmfm
from [TOP-ReID](https://github.com/924973292/TOP-ReID)

**Comment by memory541** [comment]
I use ‘52fu’ and it says ‘extraction code error’.

徐兆德
***@***.***

签名由 网易灵犀办公 定制









Original:
From：Yuhao Wang ***@***.***>Date：2024-12-26 11:26:03(中国 (GMT+08:00))To：924973292/DeMo ***@***.***>***@***.***> , Author ***@***.***>Subject：Re: [924973292/DeMo] ViT-B (Issue #4)
2024-12-26.11.25.07.png (view on web)
 The same as the bottom one.

**Comment by 924973292** [comment]
Try vmfm

**Comment by memory541** [comment]
Thanks so much, this is correct.








徐兆德
***@***.***

签名由 网易灵犀办公 定制









Original:
From：Yuhao Wang ***@***.***>Date：2024-12-26 11:49:07(中国 (GMT+08:00))To：924973292/DeMo ***@***.***>***@***.***> , Author ***@***.***>Subject：Re: [924973292/DeMo] ViT-B (Issue #4)
Try vmfm
