### ISSUE TITLE
Error in make_model.py file

### ISSUE THREAD

**Issue by IceIce1ce** [924973292/DeMo#5]
Hi authors,

Thank you for your code. When I train your model for the RGBNT201, it has an error "from basic_cnn_params.flops import give_supported_ops" in the make_model.py file. Can you check this file? Thank you.

**Comment by 924973292** [comment]
<img width="559" alt="截屏2024-12-29 17 38 23" src="https://github.com/user-attachments/assets/8a2d2f4c-67cc-42ec-9dbc-43ebe381d5a0" />

Try now

**Comment by 924973292** [comment]
`from fvcore.nn.jit_handles import elementwise_flop_counter`
 `# from modeling.fusion_part.mamba import selective_scan_flop_jit 
   def give_supported_ops():
    return{
             ...
            # No use in DeMo
            # "prim::PythonOp.SelectiveScanMamba": selective_scan_flop_jit,
            # "prim::PythonOp.SelectiveScanOflex": selective_scan_flop_jit,
            # "prim::PythonOp.SelectiveScanCore": selective_scan_flop_jit,
            # "prim::PythonOp.SelectiveScanNRow": selective_scan_flop_jit
        }
`

With the mamba... to be # in the flops file.

**Comment by IceIce1ce** [comment]
Hi author, 

In the modeling/meta_arch.py file, I also notice that there is a problem "AttributeError: 'build_transformer' object has no attribute 'fowrard_type'"

**Comment by 924973292** [comment]
Thanks for your mind, I've update the file.
The `forward_type` refers to whether a `cls` token is added in the backbone for modeling. During the early stages of the experiment, different configurations were tried, but this parameter is now redundant and has been removed. Please let me know if there are any other issues. Thank you!

**Comment by IceIce1ce** [comment]
Also, for the ViT-B-16.pt weight,can you upload it to google drive or one drive. This is because I do not have baidu account to access the weight.

**Comment by 924973292** [comment]
Hi, check this link from [Here](https://github.com/openai/CLIP/blob/main/clip/clip.py)

"ViT-B/16": "https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt"

**Comment by IceIce1ce** [comment]
Hi, 

In modeling/clip/model.py, it also have a same error: AttributeError: 'VisionTransformer' object has no attribute 'forward_type' in line 436.

**Comment by 924973292** [comment]
Ok, I fixed that, tell me if you have any other ques.

**Comment by IceIce1ce** [comment]
Hi author,

The training code is working right now. However, I also found two other issues that you need to fix. First, modeling/backbones/basis_cnn_params/__init__.py, the imported packages need to update to from modeling.backbones instead of basic_cnn_params. Second, in modeling/make_model.py file, self.generalFusion in lines 119 and 173 need to remove img_path variable.

**Comment by 924973292** [comment]
Thanks for your effort! I've fixed all the ques. you mentioned.

**Comment by IceIce1ce** [comment]
I appreciate your enthusiasm in helping me to fix the error. Thank you for your great code and congratulations on your AAAI 2025 paper.
